# -*- coding: utf-8 -*-
"""Homework_Python_III_Hilda_Meiranita_Prastika_Dewi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15LhmLDAx0dOGI3NyL2VHBUzLSHuE7Qib

# Menggunakan Class Attributes

## **Menghitung Luas Lingkaran:** 
Class Lingkaran yang memiliki attribute **radius** dan memiliki behavior **luas**. Sebuah object lingkaran dengan radius 1.
"""

import math #daftar fungsi untuk melakukan perhitungan-perhitungan matematika

class Lingkaran(): #parent class 
  #class attributes (mendefinisikan radius lingkaran=1)
  radius=1 
  #behavior (menghitung luas lingkaran)
  def luas(self): 
    return math.pi*(self.radius**2) #math.pi (mengembalikan konstanta pi dari modul math)
Luas_lingkaran=Lingkaran()
print("Luas Lingkaran: ", Luas_lingkaran.luas())

"""# **Menghitung Volume Tabung**
Class Tabung yang merupakan child class dari Lingkaran
yang memiliki attribute **tinggi** dan memiliki behavior **volume**. sebuah object tabung dengan tinggi 2
"""

#child class
class Tabung(Lingkaran): 
  #class attributes (mendefinisikan tinggi tabung=2)
  tinggi=2
  #behavior (menghitung volume tabung)
  def volume(self):
    return math.pi*(self.radius**2)*self.tinggi
Volume_tabung=Tabung()
print("Volume Tabung: ",Volume_tabung.volume())

"""# Menggunakan Instance Attribute

## **Menghitung Luas Lingkaran:**
Class Lingkaran yang memiliki attribute radius dan memiliki behavior luas. Sebuah object lingkaran dengan radius 1.
"""

#Parent class
class Lingkaran2():
  #Instance Attribute
   def __init__(self,radius2): # Menginisiasi attribute pada constructor
      self.radius2=radius2
  #Behavior luas
   def luas2(self):
      return math.pi*(self.radius2**2)

#Menghitung luas lingkaran dengan radius=1
Luas_lingkaran2 = Lingkaran2(1) 
print("Luas Lingkaran: ",Luas_lingkaran2.luas2())

"""## **Menghitung Volume Tabung**
Class Tabung yang merupakan child class dari Lingkaran yang memiliki attribute tinggi dan memiliki behavior volume. sebuah object tabung dengan tinggi 2
"""

#Child class
class tabung2(Lingkaran2):
  #Instance Attribute
   def __init__(self,radius2, tinggi2):
      super().__init__(radius2) #mengambil attribute radius pada parent class lingkaran
      self.tinggi2=tinggi2
  #Behavior volume
   def volume2(self):
      return math.pi*(self.radius2**2)*self.tinggi2

# Menghitung volume tabung dengan radius=1 dan tinggi=2
volume_tabung2= tabung2(1,2) 
print("Volume Tabung :",volume_tabung2.volume2())